# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build ...aX
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'ovos_utils/version.py'
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  update_version:
    uses: neongeckocom/.github/.github/workflows/propose_semver_release.yml@FEAT_OvosPackageSupport
    with:
      release_type: "alpha"
      version_file: ovos_utils/version.py
      alpha_var: VERSION_ALPHA
      build_var: VERSION_BUILD
      minor_var: VERSION_MINOR
      major_var: VERSION_MAJOR
      update_changelog: True
      branch: dev
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: changelog
      - name: version
        run: echo "::set-output name=version::$(python setup.py --version)"
        id: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: V${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this Release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
          commitish: dev
      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{secrets.PYPI_TOKEN}}
